# Generated by Django 3.2.12 on 2023-09-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romic_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(blank=True, default='', max_length=100)),
                ('memberemail', models.EmailField(default='', max_length=254)),
                ('memberusername', models.ImageField(default='', upload_to='images/')),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
