# Generated by Django 3.2.12 on 2023-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romic_employee', '0003_auto_20231004_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='education',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='genderequity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='sustainabledevelopment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='wash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
