# Generated by Django 3.2.12 on 2023-10-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romic_employee', '0004_auto_20231004_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='climatechange',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
