# Generated by Django 3.2.12 on 2023-10-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romic_employee', '0005_about_climatechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=10)),
                ('password', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
