# Generated by Django 3.2.12 on 2023-10-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romic_employee', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
