# Generated by Django 3.2.12 on 2023-10-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romic_employee', '0009_auto_20231014_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='climatechange',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='sustainabledevelopment',
            new_name='livelihoods',
        ),
        migrations.RemoveField(
            model_name='about',
            name='objective10',
        ),
        migrations.RemoveField(
            model_name='about',
            name='objective6',
        ),
        migrations.RemoveField(
            model_name='about',
            name='objective7',
        ),
        migrations.RemoveField(
            model_name='about',
            name='objective8',
        ),
        migrations.RemoveField(
            model_name='about',
            name='objective9',
        ),
        migrations.RemoveField(
            model_name='about',
            name='wash',
        ),
    ]
