# Generated by Django 3.2.12 on 2023-10-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romic_employee', '0010_auto_20231015_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='home',
            new_name='climatechange',
        ),
        migrations.AddField(
            model_name='about',
            name='sustainabledevelopment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
